#
#  .swiftlint.yml
#  IlluMefy
#
#  Created by Haruto K. on 2025/03/21.
#

excluded:
  - Generated

type_name:
  min_length: 4
  max_length: 60

identifier_name:
  min_length: 3
  max_length: 60

disabled_rules:
  - trailing_whitespace
  - file_length
  - identifier_name
